services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: broker-rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # web panel
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  sales-api:
    build:
      context: .
      dockerfile: Sales.Api/Dockerfile
    container_name: sales-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    depends_on:
      - rabbitmq


